[functions.track]
enabled = true
verify_jwt = false
import_map = "./functions/track/deno.json"
entrypoint = "./functions/track/index.ts"

[functions.rpg-ai-engine]
  verify_jwt = false
  import_map = "./functions/rpg-ai-engine/deno.json"
